version: "3"
services:
  postgres:
    container_name: "db"
    image: "postgres:latest"
    volumes:
        - postgredata:/var/lib/postgresql
    ports:
        - "5432:5432"
    env_file:
        - .env.local

volumes:
  postgredata: